// Blog article content extracted from deltagroupnc.com blog posts.
const SHARED = "/sites/deltagroupnc-com-daf29435/shared/images";

export interface Article { title: string; date: string; image: string; paras: string[]; }

export const ARTICLES: Record<string, Article> = {
  "young-architects": {
    "title": "Young Architects",
    "image": `${SHARED}/blog-image-2-1172x800.jpg`,
    "date": "19 February, 2022",
    "paras": [
      "Every designer takes their own time to find their style or inspiration. This lot has found itself a little sooner than the others. These ten architects have opened their creative doors and started to impact architecture and lives at a young age. These architects set an example for others and found themselves a place in this field. While their designs awe the crowd, they remain inspirations to budding architects and designers. They motivate and encourage everyone to get inspired and give inspiration to a lot more.",
      "Ne honestatis suscipiantur consequuntur mel, ut saepe consequat dissentias ius. Sit ne quas pericula deterruisset. An per feugait molestiae. Suas alia deserunt eu mea, dicant indoctum ea vix. Eu qui purto suavitate ullamcorper, vituperata cotidieque in vix. Sit dolorum civibus iracundia te. Equidem concludaturque ad has, eos facilis delicatissimi cu, no odio augue altera est."
    ]
  },
  "architecture-now": {
    "title": "Architecture Now",
    "image": `${SHARED}/blog-image-4-1172x800.jpg`,
    "date": "19 February, 2022",
    "paras": [
      "In a city where many aspects of our social lives are shaped by real estate and economic forces, architecture can play a vital role in fostering participation and belonging. New York, New Publics showcases 12 projects for public-facing spaces across New York City’s five boroughs. In contrast to the violent nature of urban renewal and other disruptive metropolitan initiatives of the past century, recent design approaches propose subtler, nimbler interventions. Considering the city as an ecosystem, these inventive approaches envision a future in which architecture creates more accessible, sustainable, and equitable cities.",
      "This exhibition brings together a wide variety of design proposals, ranging from waterfront parks, networks of public pools, and cultural spaces to local community gardens, subway stations, and virtual monuments for underrepresented populations. They reimagine the uses of civic infrastructure, the sharing of private resources, and the potential for new technologies to create virtual spaces for political engagement. Models, sketches, drawings, and photographs are featured alongside full-scale architectural components, prototypes, and an augmented-reality installation. Each project is accompanied by a newly produced video that provides a glimpse into the daily uses of these architectures.",
      "New York, New Publics features works by Adjaye Associates, Agency–Agency and Chris Woebken, CO Adaptive, James Corner Field Operations, Kinfolk Foundation, nArchitects, New Affiliates and Samuel Stewart-Halevy, Olalekan Jeyifous, Only If, Peterson Rich Office, SO – IL, SWA/Balsley, and Weiss/Manfredi. Their diverse projects imagine new and resilient ways in which communities can thrive.",
      "Organized by Evangelos Kotsioris, Assistant Curator, and Martino Stierli, The Philip Johnson Chief Curator, with Paula Vilaplana de Miguel, Curatorial Assistant, Department of Architecture and Design.",
      "New York, New Publics is the inaugural installation of Architecture Now, a new periodic exhibition series that will serve as a platform to highlight emerging talent and foreground groundbreaking projects in contemporary architecture."
    ]
  },
  "life-in-spiral": {
    "title": "Life In Spiral",
    "image": `${SHARED}/blog-image-1-1172x800.jpg`,
    "date": "19 February, 2022",
    "paras": [
      "SOURCES: The Folly National Register Nomination, the Historic Columbus archives, and Home for All by Orson Squire Fowler",
      "Victorian reformer, social critic, and phrenologist Orson Squire Fowler extolled the virtues of octagon houses in his book A Home for All. Published in 1848, the book enjoyed great popularity and went through nine printings. Many variations of octagons based on Fowler’s ideas were built, although few closely followed the book’s plans. And while Fowler believed such structures to be ideally suited for mass housing because of their potentially lower construction costs, most octagons were built for the upper-middle class. Fowler was born in 1809 in New York. He became fascinated with the then-emerging science of phrenology – studying the contours of the skull to determine one’s character. After graduating from Amherst College in 1834, he began lecturing and printing pamphlets on the subject. He was said to have a magnetic personality with piercing eyes and a long beard. He became somewhat of a celebrity and opened offices in New York City, Boston, and Philadelphia. He read the heads of well-known figures such as Horace Greeley, Walt Whitman, and President James Garfield.",
      "With phrenology paying his bills, Fowler used his fame to put forth a broader social agenda. He was an idealist with strong moral convictions, and thus he turned his attention to improving the low standard of health care and living conditions of the less fortunate. He subsequently lectured and wrote on a variety of subjects, such as education, family life, health, and farming. His phrenology studies continued to influence him and led him to the field of architecture as his next focus and forte. As he explained, every man could be his own architect. No apprenticeship was necessary if one were endowed with strong phrenological organs of INHABITIVENESS (Love of Home), and CONSTRUCTIVENESS (the ability to build); architecture was then but child’s play.",
      "It was not just the design of the octagon which intrigued Fowler, but also that it could have its plans adapted for small or large houses, and thus the basic plan could serve both the rich and the poor. Fowler claimed the octagonal structure was healthier for its occupants, less expensive to build, and more convenient than the standard housing of the day. With the same amount of wall space, the octagon plan encloses one-fifth more space than a square and one-third more than a rectangle. The octagon also uses less heat, allows in more light, and wastes less space on hallways because all rooms radiate from the center. A spiral staircase in the center of the house would also provide for the circulation of fresh air in the summer and heat in the winter. It was the air circulation that made it a healthier design in his opinion. But octagonal buildings did not originate with Fowler. The first octagons in America were part of the 17th Century Dutch settlement along the Hudson River. Colonial admirers of the form included two Virginians: George Washington, who had octagonal garden houses built at Mount Vernon, and Thomas Jefferson, who designed and built an elaborate octagon at his country retreat in Lynchburg called Poplar Forest. Shakers and other early 19th century agriculturalists also favored the shape for barns because of its efficient use of space.",
      "After the publication of Fowler’s book, octagons were constructed across the county. They ranged in size from small, one-room outbuildings to large homes like Longwood (pictured below) in Natchez. Most, however, were two-story homes built in small towns. Octagons tended to appeal to individualists and freethinkers who, like Fowler, believed they could improve their lives with better design.",
      "Fowler decided to build his own octagon home on 12 acres along the banks of the Hudson River, near Fishkill, New York. Construction began in 1848, and five years later, Fowler and his family moved into the still unfinished 90-foot-tall house. Its four stories enclosed more than 60 rooms. Remarkable features for that time included hot and cold running water, gas lights, indoor toilets, a water filtration system, speaking tubes for communicating throughout the house, and ventilators for air circulation. (It is pictured below.)",
      "Construction of octagon houses continued throughout the 1850s. Hundreds were built, many in New York, Massachusetts, and Wisconsin. The fad began to subside during the Panic of 1857, the result of over-speculation in railroads and real estate. Three years later, the beginning of the Civil War delivered the final blow to many octagon building projects, although they continued to be constructed until about 1900.",
      "Fowler’s own lavish “house of the future” ultimately became dubbed Fowler’s Folly. The Panic affected his finances, forcing him to vacate the house and rent it – only getting to live in this spectacular mansion for four years. He finally sold the house in 1859 for $150,000. While estimates vary, approximately 150 19th century octagons still stand, scattered throughout the country. Some churches and schoolhouses have remained because the form worked well for seating and acoustics. Sixty-eight octagon houses are now included in the National Register of Historic Places, some of which are open as museums. Columbus is also fortunate to have a very special octagonal house still standing.",
      "Before The Folly was The Folly, it was a non-descript, small, four-room dwelling. In April 1831, Julia Forsyth, daughter of Georgia Governor John Forsyth, married Alfred Iverson, a Princeton graduate practicing law in Columbus. The couple and his two small children by his first wife moved into the existing modest white house in the 500 block of First Avenue. Alfred had been in Georgia’s House of Representatives at the same time his future father-in-law, was the state’s Governor. Julia was the oldest of eight children and witnessed her father’s rapid rise in the political arena. Following his governorship, John Forsyth returned to the senate in 1831. He then became Secretary of State under Andrew Jackson in 1834 and continued in that post throughout Martin Van Buren’s administration.",
      "Alfred Iverson, Sr. (1798 -1873)",
      "By 1855, Alfred was elected to the U.S. Senate. He held that position until the State of Georgia seceded from the Union. Iverson remained a civilian during the Civil War, but his sons rose to the positions of Brigadier General and Lieutenant Colonel. The house that was to become The Folly was sold by the Iverson’s in 1857. It went through another owner and was then purchased by Leander May in 1862 for $400. May was a highly skilled cabinet maker and contractor. He also had an eye for the flamboyant and was aware of Fowler’s book. He then set out to catch up with the fad of octagonal houses, which had swept the country. Leander May added an octagonal front onto the Iverson cottage. He also altered the original rectangular structure to that of an octagon in order to complement the larger front home. Architecturally, The Folly has Gothic details. Its floor plan is also fairly simple with the front rooms radiating from a central fireplace. Every bit of space is utilized. The rear octagon is a back bedroom with closet and bath.",
      "There are stories that Leander May’s neighbors would ride by in their buggies as it was being built and laugh at it. It was then dubbed “May’s Folly.” Leander May transformed his home into something not seen in Columbus, and it was obviously not appreciated, yet. For unknown reasons, May sold his unique home after only living in it for three years. He sold the property in 1865 for the sum of $15,000 in Confederate Treasury Notes and $500 in gold. An interesting side note is that – it is possible that Leander going out on the “octagon limb,” so to speak, could have been Lloyd Bowers’ inspiration to add two octagonal wings on to The Elms in 1868.",
      "The Folly changed hands several times over the next hundred years. And, at some point in its long history, the house underwent yet another structural change. The original back bedroom made back into a rectangle. No one is sure when this occurred or under whose ownership, but it was probably done to enlarge the rear of the structure and perhaps encompass an existing backyard well into a back porch for the sake of convenience. The house remained a private residence and fortunately survived the growing demolition trend in the original city. During the 1940s, many property owners were moving into the Wynnton area and turning their former homes into apartments for the housing shortage during World War II. So, by the 50s and 60s – rather than keep these homes maintained, it was cheaper to pay just the property taxes on a vacant lot than to keep up the property. This pattern was slowly destroying not only the original city, but High Uptown as well.",
      "With assistance from the Junior League and $25,000 in funds, Historic Columbus created a Revolving-Redevelopment Fund in 1967. Its purpose was to enable the organization to either receive through donation or purchase an endangered property, restore it to a certain level, sell it to a sympathetic buyer, and then put the proceeds back into the fund to do it all over again. The Folly was Historic Columbus’ first property that was revolved. In 1967, Historic Columbus purchased the Folly from Freer Sheram King. That same year, Clason Kyle purchased the Walker-Peters-Langdon House on Broadway, the oldest house in Columbus, and proposed a swap. With the exchanging of the houses, Historic Columbus received what would become its first headquarters and now house museum. Clason became the owner and restorer of one of the most unique structures in town.",
      "During Mr. Kyle’s first restoration of the house in 1968, a small fire occurred in the back section of the house – which turned out to be a preservation blessing. What the fire did was to reveal that the back section was formerly octagonal in shape. Clason was also friends with the Keeper of the National Register, Bill Murtaugh, and invited him down to see the house. Bill was the one to discover that the back room was also an octagon at some point. As Bill stated, this is what makes the building so important and unique. The Folly is the only double-octagon home in the United States.",
      "Dedication of the house in 1974 as a National Historic Landmark Clason Kyle (L) and Bill Murtaugh (R)",
      "Clason restored the house and the rear room back to its octagonal shape. He lovingly maintained the property from 1967 until 2018. Its current owner, Jim Crane, has also been a wonderful steward of this special property.",
      "The Folly is truly one of Columbus’ jewels thanks to Leander May, Clason Kyle, and all who have taken care of the house through the years. It was listed as a National Historic Landmark in 1973, the highest level of recognition that can be achieved. The property also represents one of the earliest investments back into our downtown area. It’s amazing to think about all that has been accomplished, those projects still in progress, and the transformations yet to come.",
      "Next Week: We will explore the stories of the only two houses in Columbus built in the architectural style of Second Empire – the Bullard-Hart-Sampson House and the Rothschild-Pound House. Please join us!"
    ]
  }
};
