// AUTO-GENERATED by scripts/gen-delta-projects.mjs — real project data extracted
// from the Delta Group gallery manifests. Do not edit by hand.

export interface DeltaProject {
  slug: string;
  name: string;
  location: string;
  category: "Restaurant" | "Salon & Spa" | "Commercial" | "Residential";
  href: string;
  cover: string;
  gallery: string[];
  photos: number;
}

export const PROJECTS: DeltaProject[] = [
  {
    "slug": "pho-kitchen",
    "name": "Pho Kitchen",
    "location": "Morrisville, NC",
    "category": "Restaurant",
    "href": "/restaurant-construction.html#pho-kitchen-morrisville-nc",
    "cover": "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20260829_033700116_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20260829_033700116_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20260829_033704366_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20260829_033706282_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20260829_033708145_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20260829_033710236_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20260829_033712647_iOS-533x400.jpg"
    ],
    "photos": 13
  },
  {
    "slug": "asian-express-of-hope-mills",
    "name": "Asian Express of Hope Mills",
    "location": "North Carolina",
    "category": "Restaurant",
    "href": "/restaurant-construction.html#asian-express-of-hope-mills",
    "cover": "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20260819_032124908_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20260819_032124908_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20260819_032127070_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20260819_032129130_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20260819_032131058_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20260819_032133141_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20260819_032140011_iOS-533x400.jpg"
    ],
    "photos": 24
  },
  {
    "slug": "saigon-kitchen",
    "name": "Saigon Kitchen",
    "location": "321 s. Blountst., Raleigh, NC",
    "category": "Restaurant",
    "href": "/restaurant-construction.html#saigon-kitchen-321-s-blountst-raleigh-nc",
    "cover": "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20260117_021207451_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20260117_021207451_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20260117_021209336_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20260117_021211032_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20260117_021213001_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20260117_021239238_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20260117_021241445_iOS-533x400.jpg"
    ],
    "photos": 24
  },
  {
    "slug": "beer-box",
    "name": "Beer Box",
    "location": "1200 Gathering Park Circle, Cary, NC",
    "category": "Restaurant",
    "href": "/restaurant-construction.html#beer-box-1200-gathering-park-circle-cary-nc",
    "cover": "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20260117_021523314_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20260117_021523314_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20260117_021524929_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20260117_021526828_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20260117_021538507_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20260117_021540831_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20260117_021543378_iOS-533x400.jpg"
    ],
    "photos": 25
  },
  {
    "slug": "lime-lemon",
    "name": "Lime & Lemon",
    "location": "Apex Grill & Bar",
    "category": "Restaurant",
    "href": "/restaurant-construction.html#lime-lemon-apex-grill-bar",
    "cover": "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/1-2-4-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/1-2-4-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/1-3-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/1-4-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/1-5-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/1-6-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/1-7-1-533x400.jpg"
    ],
    "photos": 38
  },
  {
    "slug": "8-shots-cantina-aberdeen",
    "name": "8 Shots Cantina- Aberdeen",
    "location": "nc",
    "category": "Restaurant",
    "href": "/restaurant-construction.html#8-shots-cantina-aberdeen-nc",
    "cover": "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20251014_023123554_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20251014_023123554_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20251014_023125204_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20251014_023127423_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20251014_023131100_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20251014_023132814_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20251014_023134630_iOS-533x400.jpg"
    ],
    "photos": 37
  },
  {
    "slug": "cucciolo-famiglia",
    "name": "Cucciolo Famiglia",
    "location": "Durham, NC",
    "category": "Restaurant",
    "href": "/restaurant-construction.html#cucciolo-famiglia-durham-nc",
    "cover": "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20250926_013218676_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20250926_013218676_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20250926_013221660_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20250926_013224560_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20250926_013227279_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20250926_013230315_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20250926_013233384_iOS-533x400.jpg"
    ],
    "photos": 27
  },
  {
    "slug": "m-y-bakery-cafe",
    "name": "Mây Bakery & Cafe",
    "location": "Raleigh, NC",
    "category": "Restaurant",
    "href": "/restaurant-construction.html#m-y-bakery-cafe-raleigh-nc",
    "cover": "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20250926_014917966_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20250926_014917966_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20250926_014920045_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20250926_014922199_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20250926_014926115_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20250926_014923982_iOS-300x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20250926_014927719_iOS-300x400.jpg"
    ],
    "photos": 7
  },
  {
    "slug": "paris-banh-mi",
    "name": "Paris Banh mi",
    "location": "North Carolina",
    "category": "Restaurant",
    "href": "/restaurant-construction.html#paris-banh-mi",
    "cover": "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20240623_081444604_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20240623_081444604_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20240623_081447196_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20240623_081449563_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20240623_081451747_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20240623_081454256_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20240623_081456704_iOS-533x400.jpg"
    ],
    "photos": 25
  },
  {
    "slug": "feng-cha-tea-shop",
    "name": "Feng Cha Tea Shop",
    "location": "Wake Forest",
    "category": "Restaurant",
    "href": "/restaurant-construction.html#feng-cha-tea-shop-wake-forest",
    "cover": "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20240520_045447366_iOS-1-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20240520_045447366_iOS-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20240520_045448975_iOS-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20240520_045451096_iOS-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20240520_045452856_iOS-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20240520_045454599_iOS-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20240520_045456249_iOS-1-533x400.jpg"
    ],
    "photos": 20
  },
  {
    "slug": "bapu-tea-house-4",
    "name": "Bapu Tea House #4",
    "location": "Hanes Mall, Winston",
    "category": "Restaurant",
    "href": "/restaurant-construction.html#bapu-tea-house-4-hanes-mall-winston",
    "cover": "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20240221_030154105_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20240221_030154105_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20240221_030156205_iOS-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20240221_030157853_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20240221_030200493_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20240221_030202076_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20240221_030203844_iOS-533x400.jpg"
    ],
    "photos": 11
  },
  {
    "slug": "the-original-acai-bowl-and-smoothies",
    "name": "The Original Acai Bowl and Smoothies",
    "location": "Durham",
    "category": "Restaurant",
    "href": "/restaurant-construction.html#the-original-acai-bowl-and-smoothies-durham",
    "cover": "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20231110_060909026_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20231110_060909026_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20231110_060910875_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20231110_060912996_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20231110_060915236_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20231110_060917366_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20231110_060919457_iOS-533x400.jpg"
    ],
    "photos": 29
  },
  {
    "slug": "snacks-provision",
    "name": "Snacks Provision",
    "location": "Clayton",
    "category": "Restaurant",
    "href": "/restaurant-construction.html#snacks-provision-clayton",
    "cover": "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20231021_140105459_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20231021_140105459_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20231021_140107438_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20231021_140109691_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20231021_140117221_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20231021_140119497_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20231021_140122097_iOS-533x400.jpg"
    ],
    "photos": 26
  },
  {
    "slug": "bapu-tea-house",
    "name": "Bapu Tea House",
    "location": "Durham",
    "category": "Restaurant",
    "href": "/restaurant-construction.html#bapu-tea-house-durham",
    "cover": "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20231021_135816783_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20231021_135816783_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20231021_135818465_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20231021_135820986_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20231021_135823012_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20231021_135825128_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20231021_135827230_iOS-533x400.jpg"
    ],
    "photos": 17
  },
  {
    "slug": "kazoku-ramen-bar",
    "name": "Kazoku Ramen Bar",
    "location": "North Carolina",
    "category": "Restaurant",
    "href": "/restaurant-construction.html#kazoku-ramen-bar",
    "cover": "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20231018_142912119_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20231018_142912119_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20231018_142914237_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20231018_142916361_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20231018_142837724_iOS-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20231018_142839688_iOS-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20231018_142841734_iOS-1-533x400.jpg"
    ],
    "photos": 28
  },
  {
    "slug": "k-sandwhiches",
    "name": "k Sandwhiches",
    "location": "North Carolina",
    "category": "Restaurant",
    "href": "/restaurant-construction.html#k-sandwhiches",
    "cover": "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230804_153313810_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230804_153313810_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230804_153315985_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230804_153318007_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230804_153319885_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230804_153322021_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230804_153324449_iOS-533x400.jpg"
    ],
    "photos": 22
  },
  {
    "slug": "vivi-bubble-tea",
    "name": "Vivi Bubble Tea",
    "location": "North Carolina",
    "category": "Restaurant",
    "href": "/restaurant-construction.html#vivi-bubble-tea",
    "cover": "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230804_085628557_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230804_085628557_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230804_085631544_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230804_085635362_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230804_085640687_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230804_085644911_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230804_085648498_iOS-533x400.jpg"
    ],
    "photos": 20
  },
  {
    "slug": "share-tea-of-morrisville",
    "name": "Share Tea of Morrisville",
    "location": "North Carolina",
    "category": "Restaurant",
    "href": "/restaurant-construction.html#share-tea-of-morrisville",
    "cover": "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230716_045936244_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230716_045936244_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230716_045940174_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230716_045943011_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230716_045945831_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230716_045949650_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230716_045953135_iOS-533x400.jpg"
    ],
    "photos": 25
  },
  {
    "slug": "lechon-bbq-restaurant",
    "name": "Lechon Bbq Restaurant",
    "location": "North Carolina",
    "category": "Restaurant",
    "href": "/restaurant-construction.html#lechon-bbq-restaurant",
    "cover": "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20220124_215224192_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20220124_215224192_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20220124_215207779_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20220124_215154414_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20220124_215136323_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20220124_215132771_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20220124_215114443_iOS-533x400.jpg"
    ],
    "photos": 19
  },
  {
    "slug": "raleigh-crab-house",
    "name": "Raleigh Crab House",
    "location": "Capital Blvd, Raleigh",
    "category": "Restaurant",
    "href": "/restaurant-construction.html#raleigh-crab-house-capital-blvd-raleigh",
    "cover": "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/r8-533x400.png",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/r8-533x400.png",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/r7-533x400.png",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/r6-534x400.png",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/r5-534x400.png",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/r4-534x400.png",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/r3-534x400.png"
    ],
    "photos": 8
  },
  {
    "slug": "cajun-crab-house",
    "name": "Cajun Crab House",
    "location": "Raleigh",
    "category": "Restaurant",
    "href": "/restaurant-construction.html#cajun-crab-house-raleigh",
    "cover": "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/h8-533x400.png",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/h8-533x400.png",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/h7-533x400.png",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/h6-533x400.png",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/h5-533x400.png",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/h4-533x400.png",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/h3-533x400.png"
    ],
    "photos": 8
  },
  {
    "slug": "ff-chicken-of-briercreek",
    "name": "ff Chicken of Briercreek",
    "location": "Raleigh",
    "category": "Restaurant",
    "href": "/restaurant-construction.html#ff-chicken-of-briercreek-raleigh",
    "cover": "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230302_043156545_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230302_043156545_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230302_043158727_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230302_043203327_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230302_043205769_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230302_043216577_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230302_043224101_iOS-533x400.jpg"
    ],
    "photos": 13
  },
  {
    "slug": "fun-dippop",
    "name": "Fun Dippop",
    "location": "Instant Hot Pot & Yogurt, Raleigh",
    "category": "Restaurant",
    "href": "/restaurant-construction.html#fun-dippop-instant-hot-pot-yogurt-raleigh",
    "cover": "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230302_043659492_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230302_043659492_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230302_043702210_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230302_043704397_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230302_043706795_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230302_043712833_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230302_043720353_iOS-533x400.jpg"
    ],
    "photos": 14
  },
  {
    "slug": "milklab-s-bubble-tea-shop",
    "name": "Milklab’s Bubble Tea Shop",
    "location": "Raleigh",
    "category": "Restaurant",
    "href": "/restaurant-construction.html#milklab-s-bubble-tea-shop-raleigh",
    "cover": "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230302_041612405_iOS-800x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230302_041612405_iOS-800x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230302_041607532_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230302_041604730_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230302_041601744_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230302_041558927_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230302_041556663_iOS-533x400.jpg"
    ],
    "photos": 31
  },
  {
    "slug": "bapu-bubble-tea-house",
    "name": "Bapu Bubble Tea House",
    "location": "Crabtree Mall, Raleigh",
    "category": "Restaurant",
    "href": "/restaurant-construction.html#bapu-bubble-tea-house-crabtree-mall-raleigh",
    "cover": "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230302_043114380_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230302_043114380_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230302_043111527_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230302_043109077_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230302_043106356_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230302_043103855_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230302_043101187_iOS-533x400.jpg"
    ],
    "photos": 14
  },
  {
    "slug": "sweet-talks-cafe-desserts-apex",
    "name": "Sweet Talks Cafe & Desserts- Apex",
    "location": "nc",
    "category": "Restaurant",
    "href": "/restaurant-construction.html#sweet-talks-cafe-desserts-apex-nc",
    "cover": "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230525_192650067_iOS-1-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230525_192650067_iOS-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230525_192658226_iOS-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230525_192701756_iOS-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230525_192708003_iOS-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230525_192715116_iOS-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/restaurant-construction-html-bd1f89cf/images/20230525_192728728_iOS-1-533x400.jpg"
    ],
    "photos": 25
  },
  {
    "slug": "venice-nail-bar",
    "name": "Venice Nail Bar",
    "location": "Winterville, NC",
    "category": "Salon & Spa",
    "href": "/nail-salon-construction.html#venice-nail-bar-winterville-nc",
    "cover": "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20260117_021722793_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20260117_021722793_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20260117_021724670_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20260117_021726448_iOS-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20260117_021728196_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20260117_021729967_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20260117_021732252_iOS-533x400.jpg"
    ],
    "photos": 26
  },
  {
    "slug": "noire-the-nail-bar",
    "name": "Noire The Nail Bar",
    "location": "522 n. West Street, Raleigh, NC",
    "category": "Salon & Spa",
    "href": "/nail-salon-construction.html#noire-the-nail-bar-522-n-west-street-raleigh-nc",
    "cover": "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20260117_021816814_iOS-5-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20260117_021816814_iOS-5-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20260117_021819006_iOS-6-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20260117_021820861_iOS-7-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20260117_021822626_iOS-7-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20260117_021824649_iOS-6-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20260117_021829686_iOS-5-533x400.jpg"
    ],
    "photos": 31
  },
  {
    "slug": "royal-nails-lounge",
    "name": "Royal Nails Lounge",
    "location": "Apex",
    "category": "Salon & Spa",
    "href": "/nail-salon-construction.html#royal-nails-lounge-apex",
    "cover": "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20260117_021338462_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20260117_021338462_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20260117_021340506_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20260117_021342756_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20260117_021418380_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20260117_021424636_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20260117_021426440_iOS-533x400.jpg"
    ],
    "photos": 31
  },
  {
    "slug": "therapy-nail-spa",
    "name": "Therapy Nail Spa",
    "location": "Cary, NC",
    "category": "Salon & Spa",
    "href": "/nail-salon-construction.html#therapy-nail-spa-cary-nc",
    "cover": "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20250926_051646681_iOS-1-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20250926_051646681_iOS-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20250926_051648623_iOS-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20250926_051650765_iOS-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20250926_051652588_iOS-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20250926_051654190_iOS-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20250926_051657359_iOS-1-533x400.jpg"
    ],
    "photos": 20
  },
  {
    "slug": "k-nail-bar",
    "name": "K-nail Bar",
    "location": "Greenville, NC",
    "category": "Salon & Spa",
    "href": "/nail-salon-construction.html#k-nail-bar-greenville-nc",
    "cover": "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20250926_051603765_iOS-1-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20250926_051603765_iOS-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20250926_051605956_iOS-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20250926_051607835_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20250926_051609711_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20250926_051611996_iOS-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20250926_051613828_iOS-1-533x400.jpg"
    ],
    "photos": 21
  },
  {
    "slug": "deliciae-nails",
    "name": "Deliciae Nails",
    "location": "Holly Springs, NC",
    "category": "Salon & Spa",
    "href": "/nail-salon-construction.html#deliciae-nails-holly-springs-nc",
    "cover": "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20250111_041553094_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20250111_041553094_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20250111_041555226_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20250111_041557158_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20250111_041559279_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20250111_041601366_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20250111_041603210_iOS-533x400.jpg"
    ],
    "photos": 20
  },
  {
    "slug": "nails-social-of-winston",
    "name": "Nails Social of Winston",
    "location": "Winston Salem, NC",
    "category": "Salon & Spa",
    "href": "/nail-salon-construction.html#nails-social-of-winston-winston-salem-nc",
    "cover": "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20250109_063621804_iOS-2-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20250109_063621804_iOS-2-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20250109_063624932_iOS-1-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20250109_063627229_iOS-1-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20250109_063629797_iOS-1-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20250109_063631989_iOS-1-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20250109_063634591_iOS-1-1-533x400.jpg"
    ],
    "photos": 28
  },
  {
    "slug": "envy-nail-spa",
    "name": "Envy Nail Spa",
    "location": "Wendell",
    "category": "Salon & Spa",
    "href": "/nail-salon-construction.html#envy-nail-spa-wendell",
    "cover": "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20240520_041657769_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20240520_041657769_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20240520_041659806_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20240520_041703530_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20240520_041705270_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20240520_041706976_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20240520_041709457_iOS-533x400.jpg"
    ],
    "photos": 31
  },
  {
    "slug": "posh-nail-spa-of-durham",
    "name": "Posh Nail Spa of Durham",
    "location": "North Carolina",
    "category": "Salon & Spa",
    "href": "/nail-salon-construction.html#posh-nail-spa-of-durham",
    "cover": "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20231110_060652067_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20231110_060652067_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20231110_060654924_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20231110_060658111_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20231110_060700612_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20231110_060703483_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20231110_060705594_iOS-533x400.jpg"
    ],
    "photos": 45
  },
  {
    "slug": "valentino-nails-bar",
    "name": "Valentino Nails Bar",
    "location": "North Carolina",
    "category": "Salon & Spa",
    "href": "/nail-salon-construction.html#valentino-nails-bar",
    "cover": "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20220308_141414410_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20220308_141414410_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20220302_162004856_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20220302_161959181_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20220308_142836147_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20220308_142721134_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20220308_141736445_iOS-533x400.jpg"
    ],
    "photos": 22
  },
  {
    "slug": "uq-nails",
    "name": "uq Nails",
    "location": "North Carolina",
    "category": "Salon & Spa",
    "href": "/nail-salon-construction.html#uq-nails",
    "cover": "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20220130_210235039_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20220130_210235039_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20220130_205802446_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20220130_205752321_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20220130_205746800_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20220130_205704808_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20220130_204548102_iOS-533x400.jpg"
    ],
    "photos": 19
  },
  {
    "slug": "tip-top-nails",
    "name": "Tip Top Nails",
    "location": "North Carolina",
    "category": "Salon & Spa",
    "href": "/nail-salon-construction.html#tip-top-nails",
    "cover": "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20210713_155107964_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20210713_155107964_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20210713_165433036_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20210713_155053102_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20210713_155025801_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20210713_154934855_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20210713_154902412_iOS-533x400.jpg"
    ],
    "photos": 19
  },
  {
    "slug": "sabrina-s-nails",
    "name": "Sabrina’s Nails",
    "location": "North Carolina",
    "category": "Salon & Spa",
    "href": "/nail-salon-construction.html#sabrina-s-nails",
    "cover": "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20210422_180439746_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20210422_180439746_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20210422_180425201_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20210422_180333749_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20210422_180329054_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20210422_180314492_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20210422_180306603_iOS-533x400.jpg"
    ],
    "photos": 15
  },
  {
    "slug": "noire-the-nail-bar-of-southpoint-mall",
    "name": "Noire The Nail Bar of Southpoint Mall",
    "location": "Durham",
    "category": "Salon & Spa",
    "href": "/nail-salon-construction.html#noire-the-nail-bar-of-southpoint-mall-durham",
    "cover": "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20211208_234520823_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20211208_234520823_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20211208_233348647_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20211208_233320973_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20211208_233301791_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20211208_233245094_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20211208_233100382_iOS-533x400.jpg"
    ],
    "photos": 35
  },
  {
    "slug": "magic-nails",
    "name": "Magic Nails",
    "location": "Independence Mall",
    "category": "Salon & Spa",
    "href": "/nail-salon-construction.html#magic-nails-independence-mall",
    "cover": "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20210302_151634000_iOS-711x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20210302_151634000_iOS-711x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20210302_144712000_iOS-711x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20210302_143115000_iOS-711x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20210302_134315000_iOS-711x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20210302_134315000_iOS-1-711x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20210302_134314000_iOS-711x400.jpg"
    ],
    "photos": 69
  },
  {
    "slug": "nails-rustique-of-cary",
    "name": "Nails Rustique of Cary",
    "location": "North Carolina",
    "category": "Salon & Spa",
    "href": "/nail-salon-construction.html#nails-rustique-of-cary",
    "cover": "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20210723_133957452_iOS-1-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20210723_133957452_iOS-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20210723_133944670_iOS-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20210723_164048685_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20210723_164033226_iOS-676x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20210723_134108190_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20210723_134059529_iOS-533x400.jpg"
    ],
    "photos": 18
  },
  {
    "slug": "joja-nails",
    "name": "Joja Nails",
    "location": "Downtown Raleigh",
    "category": "Salon & Spa",
    "href": "/nail-salon-construction.html#joja-nails-downtown-raleigh",
    "cover": "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/52-533x400.png",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/52-533x400.png",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/55-533x400.png",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/54-533x400.png",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/51-533x400.png",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/50-533x400.png",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/49-533x400.png"
    ],
    "photos": 8
  },
  {
    "slug": "new-york-nails",
    "name": "New York Nails",
    "location": "Jacksonville Mall",
    "category": "Salon & Spa",
    "href": "/nail-salon-construction.html#new-york-nails-jacksonville-mall",
    "cover": "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/p8-711x400.webp",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/p8-711x400.webp",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/p7-711x400.webp",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/p4-711x400.webp",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/p1-711x400.webp",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/p6-583x400.webp",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/p5-571x400.webp"
    ],
    "photos": 8
  },
  {
    "slug": "lavish-nails",
    "name": "Lavish Nails",
    "location": "North Carolina",
    "category": "Salon & Spa",
    "href": "/nail-salon-construction.html#lavish-nails",
    "cover": "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20220221_232825329_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20220221_232825329_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20220221_233039156_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20220221_233051313_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20220221_233214590_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20220221_233323287_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20220221_233335772_iOS-533x400.jpg"
    ],
    "photos": 10
  },
  {
    "slug": "west-and-nails-salon",
    "name": "West and Nails Salon",
    "location": "Clayton",
    "category": "Salon & Spa",
    "href": "/nail-salon-construction.html#west-and-nails-salon-clayton",
    "cover": "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20230302_042318997_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20230302_042318997_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20230302_042323539_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20230302_042327240_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20230302_042329776_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20230302_042335161_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/nail-salon-construction-html-1c54b6a2/images/20230302_042337979_iOS-533x400.jpg"
    ],
    "photos": 18
  },
  {
    "slug": "image-studios-of-durham",
    "name": "Image Studios of Durham",
    "location": "nc",
    "category": "Commercial",
    "href": "/commercial-construction.html#image-studios-of-durham-nc",
    "cover": "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20260819_032237040_iOS-1-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20260819_032237040_iOS-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20260819_032241326_iOS-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20260819_032245065_iOS-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20260819_032246768_iOS-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20260819_032251642_iOS-1-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20260819_032259643_iOS-1-533x400.jpg"
    ],
    "photos": 23
  },
  {
    "slug": "playa-bowls",
    "name": "Playa Bowls",
    "location": "Apex, NC",
    "category": "Commercial",
    "href": "/commercial-construction.html#playa-bowls-apex-nc",
    "cover": "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20250926_014847687_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20250926_014847687_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20250926_014850068_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20250926_014852249_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20250926_014854528_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20250926_014856702_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20250926_014859067_iOS-533x400.jpg"
    ],
    "photos": 12
  },
  {
    "slug": "church-of-raleigh",
    "name": "Church of Raleigh",
    "location": "North Carolina",
    "category": "Commercial",
    "href": "/commercial-construction.html#church-of-raleigh",
    "cover": "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20250309_234926826_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20250309_234926826_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20250309_234929357_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20250309_234931509_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20250309_234933618_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20250309_234935726_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20250309_234938018_iOS-533x400.jpg"
    ],
    "photos": 33
  },
  {
    "slug": "beyond-movement-physical-therapy",
    "name": "Beyond Movement Physical Therapy",
    "location": "Clayton",
    "category": "Commercial",
    "href": "/commercial-construction.html#beyond-movement-physical-therapy-clayton",
    "cover": "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20240520_041618711_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20240520_041618711_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20240520_041620784_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20240520_041622451_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20240520_041624149_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20240520_041625929_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20240520_041628477_iOS-533x400.jpg"
    ],
    "photos": 15
  },
  {
    "slug": "mad-splatter-paint-studio",
    "name": "Mad Splatter Paint Studio",
    "location": "Apex",
    "category": "Commercial",
    "href": "/commercial-construction.html#mad-splatter-paint-studio-apex",
    "cover": "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20231101_061452016_iOS-701x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20231101_061452016_iOS-701x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20231101_061446781_iOS-535x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20231101_061449048_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20231101_061454704_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20231101_061457011_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20231101_061459750_iOS-533x400.jpg"
    ],
    "photos": 9
  },
  {
    "slug": "color-dark-shell-office",
    "name": "Color Dark Shell Office",
    "location": "North Carolina",
    "category": "Commercial",
    "href": "/commercial-construction.html#color-dark-shell-office",
    "cover": "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20231018_143049483_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20231018_143049483_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20231018_143051566_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20231018_143054622_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20231018_143149110_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20231018_143151760_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20231018_143158044_iOS-533x400.jpg"
    ],
    "photos": 24
  },
  {
    "slug": "project-lean-nation-of-north-raleigh",
    "name": "Project Lean Nation of North Raleigh",
    "location": "North Carolina",
    "category": "Commercial",
    "href": "/commercial-construction.html#project-lean-nation-of-north-raleigh",
    "cover": "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20231018_143024199_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20231018_143024199_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20231018_143026254_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20231018_143028546_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20231018_143030912_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20231018_143032868_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20231018_143035019_iOS-533x400.jpg"
    ],
    "photos": 12
  },
  {
    "slug": "laser-office",
    "name": "Laser Office",
    "location": "North Carolina",
    "category": "Commercial",
    "href": "/commercial-construction.html#laser-office",
    "cover": "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20220412_140131426_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20220412_140131426_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20220412_140137873_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20220412_140414183_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20220412_140424239_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20220412_140435144_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20220412_140445971_iOS-533x400.jpg"
    ],
    "photos": 31
  },
  {
    "slug": "west-end-clubhouse",
    "name": "West End Clubhouse",
    "location": "North Carolina",
    "category": "Commercial",
    "href": "/commercial-construction.html#west-end-clubhouse",
    "cover": "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20220314_154028754_iOS-533x400.jpg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20220314_154028754_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20220314_144052460_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20220314_153415951_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20220314_153405292_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20220314_152834733_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/20220314_152823053_iOS-533x400.jpg"
    ],
    "photos": 62
  },
  {
    "slug": "triangle-park-apts-clubhouse",
    "name": "Triangle Park Apts Clubhouse",
    "location": "Durham",
    "category": "Commercial",
    "href": "/commercial-construction.html#triangle-park-apts-clubhouse-durham",
    "cover": "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/37-533x400.png",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/37-533x400.png",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/36-533x400.png",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/35-533x400.png",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/34-533x400.png",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/33-533x400.png",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/32-533x400.png"
    ],
    "photos": 8
  },
  {
    "slug": "thirsty-skull",
    "name": "Thirsty Skull",
    "location": "Brewery of Siler City",
    "category": "Commercial",
    "href": "/commercial-construction.html#thirsty-skull-brewery-of-siler-city",
    "cover": "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/27-1-533x400.jpeg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/27-1-533x400.jpeg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/25-1-533x400.jpeg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/16-1-533x400.jpeg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/15-1-533x400.jpeg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/14-1-533x400.jpeg",
      "/sites/deltagroupnc-com-daf29435/commercial-construction-html-1a4582f0/images/13-1-533x400.jpeg"
    ],
    "photos": 8
  },
  {
    "slug": "gaston-lake",
    "name": "Gaston Lake",
    "location": "Eatons Crossing",
    "category": "Residential",
    "href": "/residential-construction.html#gaston-lake-eatons-crossing",
    "cover": "/sites/deltagroupnc-com-daf29435/residential-construction-html-491a1682/images/89-711x400.jpeg",
    "gallery": [
      "/sites/deltagroupnc-com-daf29435/residential-construction-html-491a1682/images/89-711x400.jpeg",
      "/sites/deltagroupnc-com-daf29435/residential-construction-html-491a1682/images/88-711x400.jpeg",
      "/sites/deltagroupnc-com-daf29435/residential-construction-html-491a1682/images/20240221_025635866_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/residential-construction-html-491a1682/images/20240221_025639628_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/residential-construction-html-491a1682/images/20240221_025651123_iOS-533x400.jpg",
      "/sites/deltagroupnc-com-daf29435/residential-construction-html-491a1682/images/20240221_025654312_iOS-533x400.jpg"
    ],
    "photos": 43
  }
];

export const CATEGORIES = ["Restaurant", "Salon & Spa", "Commercial", "Residential"] as const;
